DM-37478: migrating to model packages
lsst-dm/rbClassifier_data pull request #1
Opened 2023-01-24 05:17 UTC by NimSed

Migrating to model packages. Main changes have been applied to the meas_transiNet repository, and this pull request only contains minor necessary changes to keep the two repositories compatible.

2023-02-27 21:38 UTC, kfindeisen requested changes
Most of the changes look fine, but I'm concerned that the tests don't correspond to the latest API on lsst/meas_transiNet#12. Do they really pass in their current form?

2023-02-27 21:38 UTC, kfindeisen commented on rbResnet50-DC2/rbResnet50.py
> +        self.resnet = resnet50(weights=None)
Is this happening alongside an update to our version of `torchvision`, or is this a past incompatibility that we missed for lack of testing?

2023-02-27 21:38 UTC, kfindeisen commented on rbResnet50-DC2/rbResnet50.py
>      def __init__(self):
Can the DOI link in the comment above be replaced with a published Microsoft(?) report?

2023-02-27 21:38 UTC, kfindeisen commented on model_packages/rbResnet50-DC2/test.py
> +        model_package = NNModelPackage(self.model_package_name)
The URI-based API for `NNModelPackage` is out of date, please update accordingly and verify the tests.

2023-02-27 21:38 UTC, kfindeisen commented on model_packages/rbResnet50-DC2/test.py
> +        model_package = NNModelPackage(self.model_package_name)
How is this test run, anyway? I see that `rbClassifier_data` is buildable with Scons, but this organization of tests won't work with the default LSST tooling. If you can't set up a custom Scons runner for these tests, then moving them into per-model files in a `tests/` directory is probably better than not running them at all.

2023-02-27 21:38 UTC, kfindeisen commented on model_packages/rbResnet50-DC2/test.py
> +        self.assertAlmostEqual(result[0], 0.00042127)  # Empirical meaningless value spit by this very model
Maybe reword the comment to "Test for consistency with past behavior, given the same inputs and weights"?

2023-02-27 21:38 UTC, kfindeisen commented on model_packages/rbResnet50-DC2/test.py
> +class TestOneCutout(unittest.TestCase):
As in `meas_transiNet`, why have a separate class for this test? The current arrangement requires duplicating the setup code for each test case, which defeats the point of having a `SetUp`.

2023-03-23 21:42 UTC, NimSed commented on rbResnet50-DC2/rbResnet50.py
> +        self.resnet = resnet50(weights=None)
Yes, the former.

2023-03-23 22:01 UTC, NimSed commented on model_packages/rbResnet50-DC2/test.py
> +        model_package = NNModelPackage(self.model_package_name)
This is the resurrected test, being stored there for potential future reference -- i.e. is not currently being called/run by anyone.
But I'm going to apply the suggested fixes and make it runnable.

2023-03-23 22:13 UTC, NimSed commented on model_packages/rbResnet50-DC2/test.py
> +        self.assertAlmostEqual(result[0], 0.00042127)  # Empirical meaningless value spit by this very model
I see this comment's purpose more as an answer to some one who asks what is "0.00042127". Let's leave it?

2023-03-23 22:13 UTC, NimSed commented on model_packages/rbResnet50-DC2/test.py
> +class TestOneCutout(unittest.TestCase):
I added a comment implicitly explaining why this needs a different setup.

2023-03-23 22:23 UTC, kfindeisen commented on model_packages/rbResnet50-DC2/test.py
> +class TestOneCutout(unittest.TestCase):
Sorry, which comment? I don't see it...

2023-03-23 22:27 UTC, NimSed commented on model_packages/rbResnet50-DC2/test.py
> +class TestOneCutout(unittest.TestCase):
In the docstrings of the classes. Or have I not pushed it?

2023-03-23 22:34 UTC, kfindeisen approved these changes
I'm still not happy about leaving the tests un-run, but my only outstanding comment is about clarifying why there are two test suites.

2023-03-23 22:34 UTC, kfindeisen commented on model_packages/rbResnet50-DC2/test.py
> +class TestOneCutout(unittest.TestCase):
After some discussion on Slack, I finally understood that this test focuses on use of the model with `RBTransiNetInterface`, while the other focuses on its use with `NNModelPackage`. I think the parallel structure would be clearer if `TestOneCutout` were renamed to something analogous to `TestModelPackageNeighbor`; perhaps `TestTransiNetInterface`?

2023-03-23 22:55 UTC, NimSed commented on model_packages/rbResnet50-DC2/test.py
> +class TestOneCutout(unittest.TestCase):
Right. Just renamed both to something more meaningful.

2023-03-23 23:02 UTC, merged